apiVersion: v1
kind: Pod
metadata:
  name: frontend-1
spec: 
  containers:
  - name: app
    image: nginx
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m" 
